POST http://localhost:3001/api/register
Content-Type: application/json

{
   "email":"userxxx@test.com",
   "username":"lia",
   "userPassword":"5555",
   "userPassword2":"5555"
}
###

POST http://localhost:3001/api/loginUser
Content-Type: application/json

{
   "email":"userxxx@test.com",
   "userPassword":"5555"
} 

###

POST http://localhost:3001/api/createUserRole
Content-Type: application/json

{
   "user_id":"ea00ea6f-5a60-4c00-9d40-31f866205899",
   "role_id":"6860040e-24e7-428d-a67b-8dfd103e290d"
} 

###
GET  http://localhost:3001/api/readRoles
Content-Type: application/json

{
   "page":"1"
} 

###


GET  http://localhost:3001/api/login-sso
Content-Type: application/json

{
  
} 
###

DELETE  http://localhost:3001/api/logout
Content-Type: application/json

{
  
} 
//CRUD
###
PUT  http://localhost:3001/api/updateUser
Content-Type: application/json

{
   "id":"80089cb4-8202-45c3-b1e8-1d9ce638ad2c",
   "jabatanId":"e67f3d36-05de-4c9d-9093-741b48bdaec3"
} 
###
DELETE  http://localhost:3001/api/deletePermission
Content-Type: application/json

{
   "id":"f4ac4348-3a7a-4f35-bf19-71ead1b03ae7"
} 
###
GET  http://localhost:3001/api/readPermission
Content-Type: application/json

{
   "page":"1"
} 
###
POST  http://localhost:3001/api/createUser
Content-Type: application/json

{
  "username":"user123@test.com",
  "email":"user123@test.com",
  "password":"1234"

} 
###

POST  http://localhost:3001/api/createRoles
Content-Type: application/json

{
  "name":"Almighty789323",
  "description":"Grant Almighty Power, use it wisely",
  "system_environment":"USER"

} 
###
POST  http://localhost:3001/api/createPermission
Content-Type: application/json

{
  "name":"Read Allsa",
  "description":"admin-crud_doc",
  "system_environment":"USER"
} 
###
POST  http://localhost:3001/api/RolePerm
Content-Type: application/json

{
   "role_id":"e996346a-4804-4197-ad10-bc4e210154e3",
   "permission_id":"529e2f97-c645-440a-9e83-5bd8d96a4858"
} 
###
DELETE  http://localhost:3001/api/deleteUserRole
Content-Type: application/json

{
   "role_id":"dd188417-9b8f-46f4-ba2a-f36cda5e5d3f",
   "user_id":"80089cb4-8202-45c3-b1e8-1d9ce638ad2c"
} 
###
GET  http://localhost:3001/api/searchUser
Content-Type: application/json

{
  "id":"80089cb4-8202-45c3-b1e8-1d9ce638ad2c"
} 
###
POST  http://localhost:3001/api/createJabatan
Content-Type: application/json

{
   "name":"Test",
   "description":"Test",
   "level":"2"
} 
###
DELETE  http://localhost:3001/api/deleteUser
Content-Type: application/json

{
   "id":"ed17dd42-0ae5-4c56-9a6d-c5bf32330ba2"
} 
###
DELETE  http://localhost:3001/api/deleteRoles
Content-Type: application/json

{
 "id":"dd188417-9b8f-46f4-ba2a-f36cda5e5d3f"
} 
###
DELETE  http://localhost:3001/api/deletePermission
Content-Type: application/json

{
 "id":"30a6cdaf-c761-43b4-870e-8d125b0b03d0"
} 